apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffchecker
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # don't create extra pods during update
      maxUnavailable: 1  # terminate one old pod first, then start new one
  selector:
    matchLabels:
      app: diffchecker
  template:
    metadata:
      labels:
        app: diffchecker
    spec:
      containers:
        - name: diffchecker
          image: ghcr.io/rd-95/diffchecker:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
